'use client';
import {useRef,useState,type CSSProperties} from 'react';
import {UserRound,Building2,FileText,MapPin,AtSign,CalendarDays,Video,Plus,Minus,RotateCcw,Move,MousePointer2,ScanLine,ZoomIn,Maximize,ChevronRight} from 'lucide-react';
import {entities,connections,cameras,colors,groups,type Entity,type Connection,type EntityType} from './demo-data';
export const typeIcon:Record<EntityType,typeof UserRound>={person:UserRound,organization:Building2,document:FileText,location:MapPin,account:AtSign,event:CalendarDays};
export function Glyph({entity,size=16}:{entity:Entity;size?:number}){const Icon=typeIcon[entity.type];return <Icon size={size}/>;}
export function Spark({values,color='currentColor'}:{values:number[];color?:string}){const max=Math.max(...values,1);return <svg className="spark" viewBox="0 0 110 30" aria-hidden="true"><path d={values.map((v,i)=>`${i?'L':'M'}${i*110/(values.length-1)} ${28-v/max*24}`).join(' ')} fill="none" stroke={color} strokeWidth="1.5"/><path d="M0 29H110" stroke="currentColor" opacity=".15"/></svg>;}
export function GraphCanvas({nodes,edges,selected,onSelect,onRelation,activeRelation,labels,dim,path,layout,motion}:{nodes:Entity[];edges:Connection[];selected:string;onSelect:(id:string)=>void;onRelation:(id:string)=>void;activeRelation:string;labels:boolean;dim:boolean;path:string[];layout:string;motion:boolean}){
 const [zoom,setZoom]=useState(1);const [pan,setPan]=useState({x:0,y:0});const [positions,setPositions]=useState<Record<string,{x:number;y:number}>>({});const [hand,setHand]=useState(false);
 const scene=useRef<HTMLDivElement>(null);const drag=useRef<{id?:string;x:number;y:number;ox:number;oy:number;moved:boolean}|null>(null);const suppressed=useRef(false);
 const allTypes:EntityType[]=['person','organization','document','account','event','location'];
 const pos=(e:Entity)=>positions[e.id]||(layout==='columns'?{x:9+allTypes.indexOf(e.type)*16,y:10+entities.filter(n=>n.type===e.type).findIndex(n=>n.id===e.id)*14}:{x:e.x,y:e.y});
 const related=new Set([selected,...edges.filter(e=>e.from===selected||e.to===selected).flatMap(e=>[e.from,e.to])]);
 function begin(e:React.PointerEvent,id?:string){if((e.target as HTMLElement).closest('.graph-tools,.edge-tag'))return;const p=id?pos(entities.find(n=>n.id===id)!):pan;drag.current={id,x:e.clientX,y:e.clientY,ox:p.x,oy:p.y,moved:false};suppressed.current=false;e.currentTarget.setPointerCapture(e.pointerId);}
 function move(e:React.PointerEvent){const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>5)d.moved=true;if(d.id){const box=scene.current?.getBoundingClientRect();if(box)setPositions(p=>({...p,[d.id!]:{x:Math.max(3,Math.min(97,d.ox+dx/box.width*100)),y:Math.max(3,Math.min(93,d.oy+dy/box.height*100))}}));}else setPan({x:d.ox+dx,y:d.oy+dy});}
 function end(){suppressed.current=!!drag.current?.moved;drag.current=null;}
 const pathEdges=path.slice(1).map((n,i)=>[path[i],n]);
 return <div className={`network-canvas ${hand?'pan-mode':''}`} onPointerDown={e=>begin(e)} onPointerMove={move} onPointerUp={end}>
  <div className="canvas-coordinates"><span>NETWORK / RELATIONAL SPACE</span><span>PX–01 / V.02</span></div>
  <div className="graph-scene" ref={scene} style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}>
   {layout==='network'&&<><div className="cluster family-cluster"><span>01 / FAMILY</span></div><div className="cluster social-cluster"><span>02 / SOCIAL CONTEXT</span></div><div className="cluster professional-cluster"><span>03 / RESEARCH NETWORK</span></div><div className="root-orbit" style={{left:`${pos(entities[0]).x}%`,top:`${pos(entities[0]).y}%`}}/></>}
   <svg className="network-lines" viewBox="0 0 1000 600" preserveAspectRatio="none" aria-label="Relationship connections">
    <defs><pattern id="edge-dot" width="4" height="4" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".5" fill="#53626b"/></pattern></defs>
    {edges.map((edge,i)=>{const a=pos(entities.find(e=>e.id===edge.from)!),b=pos(entities.find(e=>e.id===edge.to)!);const x=a.x*10,y=a.y*6,tx=b.x*10,ty=b.y*6;const curved=edge.id==='r09';const d=curved?`M ${x} ${y} Q ${(x+tx)/2} ${(y+ty)/2+50} ${tx} ${ty}`:`M ${x} ${y} L ${tx} ${ty}`;const focused=edge.from===selected||edge.to===selected;const isPath=pathEdges.some(([f,t])=>(edge.from===f&&edge.to===t)||(edge.from===t&&edge.to===f));const emphasis=path.length?isPath:focused;return <g key={edge.id} className={`connection ${emphasis?'emphasis':''} ${activeRelation===edge.id?'current-event':''} ${edge.status} ${dim&&!focused?'dimmed':''}`} style={{'--edge-color':groups[edge.group].color} as CSSProperties}>
     <path d={d} className="edge-line" vectorEffect="non-scaling-stroke"/>
     {motion&&<path d={d} className="edge-flow" pathLength="100" style={{animationDelay:`-${i*.37}s`,animationDuration:`${5+i%4}s`}} vectorEffect="non-scaling-stroke"/>}
     <path d={d} className="edge-hit" onPointerDown={e=>e.stopPropagation()} onClick={()=>onRelation(edge.id)}><title>{`${edge.label} · ${edge.status} · ${edge.source}`}</title></path>
    </g>;})}
   </svg>
   {labels&&edges.filter(e=>e.from===selected||e.to===selected).map(edge=>{const a=pos(entities.find(e=>e.id===edge.from)!),b=pos(entities.find(e=>e.id===edge.to)!);const left=(a.x+b.x)/2,top=(a.y+b.y)/2+(edge.id==='r09'?7:0);return <button key={edge.id} className={`edge-tag ${edge.status}`} style={{left:`${left}%`,top:`${top}%`,color:groups[edge.group].color}} onClick={()=>onRelation(edge.id)}>{edge.status==='disputed'?'! ':''}{edge.label}<ChevronRight size={9}/></button>;})}
   {nodes.map(entity=>{const p=pos(entity);const focused=entity.id===selected;const pathDim=path.length&&!path.includes(entity.id);return <button key={entity.id} className={`network-node ${entity.id==='alex'?'seed-node':''} ${focused?'selected':''} ${entity.type} ${(dim&&!related.has(entity.id))||pathDim?'faded':''}`} style={{left:`${p.x}%`,top:`${p.y}%`,'--node-color':colors[entity.type]} as CSSProperties} onPointerDown={e=>{e.stopPropagation();begin(e,hand?undefined:entity.id);}} onClick={()=>{if(!suppressed.current)onSelect(entity.id);}} aria-label={`Inspect ${entity.name}`}>
    <span className="node-body">{entity.initials||<Glyph entity={entity} size={17}/>}<i className="node-port"/>{entity.id==='alex'&&<span className="node-brackets"/>}</span><strong>{entity.name}</strong><small>{entity.subtitle}</small>
   </button>;})}
  </div>
  {!nodes.length&&<div className="empty-canvas">No entities match these filters.<small>Try a lower evidence threshold or another lens.</small></div>}
  <div className="canvas-legend"><span><i style={{background:groups.family.color}}/>Family</span><span><i style={{background:groups.social.color}}/>Social</span><span><i style={{background:groups.professional.color}}/>Professional</span><span className="dashed-key">Unresolved claim</span></div>
  <div className="graph-tools" onPointerDown={e=>e.stopPropagation()}><button aria-label="Select and drag entities" className={!hand?'active':''} onClick={()=>setHand(false)}><MousePointer2 size={15}/></button><button aria-label="Pan canvas" className={hand?'active':''} onClick={()=>setHand(true)}><Move size={15}/></button><i/><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.55,z-.1))}><Minus size={15}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(1.8,z+.1))}><Plus size={15}/></button><i/><button aria-label="Reset canvas" onClick={()=>{setPan({x:0,y:0});setPositions({});setZoom(1);}}><Maximize size={15}/></button></div>
  <div className="canvas-scale"><span/>RELATIONAL DISTANCE ≠ PHYSICAL DISTANCE</div>
 </div>;
}
export function GeoMap({large=false,selected='CAM-01',onSelect,coverage=true,motion=true}:{large?:boolean;selected?:string;onSelect?:(id:string)=>void;coverage?:boolean;motion?:boolean}){
 const [zoom,setZoom]=useState(1);const [offset,setOffset]=useState({x:0,y:0});const dragging=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);
 return <div className={`geo-map ${large?'large-map':''}`}>
  <div className="map-stage" style={{transform:`translate(${offset.x}px,${offset.y}px) scale(${zoom})`}} onPointerDown={e=>{if((e.target as HTMLElement).closest('button,a'))return;dragging.current={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=dragging.current;if(d)setOffset({x:d.ox+e.clientX-d.x,y:d.oy+e.clientY-d.y});}} onPointerUp={()=>dragging.current=null}>
   <div className="map-tiles">{Array.from({length:12},(_,i)=><img key={i} src={`/maps/${4091+i%4}-${2723+Math.floor(i/4)}.png`} alt="" draggable={false}/>)}</div><div className="map-grid"/>
   {coverage&&cameras.map((c,i)=><div key={c.id} className={`coverage-disc coverage-${i} ${motion?'sweeping':''}`} style={{left:`${c.x}%`,top:`${c.y}%`}}><span/></div>)}
   {cameras.map(c=><button key={c.id} className={`map-marker ${selected===c.id?'selected':''}`} style={{left:`${c.x}%`,top:`${c.y}%`}} onClick={()=>onSelect?.(c.id)} aria-label={`Inspect ${c.id} ${c.name}`}><Video size={large?17:11}/>{large&&<span>{c.id}<small>{c.status==='Not connected'?'OFFLINE':'SIMULATED'}</small></span>}</button>)}
   {large&&<><span className="map-district" style={{left:'17%',top:'30%'}}>WESTMINSTER</span><span className="map-district" style={{left:'55%',top:'70%'}}>SOUTH BANK</span><span className="map-river">RIVER THAMES</span></>}
  </div><span className="north-arrow">N<br/>↑</span>
  <div className="map-attribution"><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap</a></div>
  {large&&<div className="map-controls"><button aria-label="Zoom map in" onClick={()=>setZoom(z=>Math.min(2.5,z+.2))}><Plus size={17}/></button><button aria-label="Zoom map out" onClick={()=>setZoom(z=>Math.max(.75,z-.2))}><Minus size={17}/></button><button aria-label="Reset map" onClick={()=>{setZoom(1);setOffset({x:0,y:0});}}><RotateCcw size={16}/></button></div>}
 </div>;
}
export function CameraScene({index=0,boxes=true,zones=true}:{index?:number;boxes?:boolean;zones?:boolean}){return <div className={`camera-scene scene-${index}`}>
 {index===2?<div className="source-offline"><Video size={26}/><b>NO SOURCE CONNECTED</b><small>DESIGNATED SLOT / CAM-03</small></div>:<svg viewBox="0 0 600 340" preserveAspectRatio="xMidYMid slice" aria-label="Synthetic controlled test scene">
 <defs><pattern id={`floor-${index}`} width="55" height="35" patternUnits="userSpaceOnUse" patternTransform="skewX(-25)"><path d="M0 0H55V35" fill="none" stroke="#57645c" strokeWidth=".6"/></pattern></defs>
 <rect width="600" height="340" fill="#151e1c"/><path d="M0 0H600V128L345 113 0 158Z" fill="#202b27"/><path d="M0 170 600 124V340H0Z" fill={`url(#floor-${index})`}/><path d="M0 159 340 114 600 129M340 0V114" fill="none" stroke="#69766b" strokeWidth="1.2"/>
 <g fill="#28372e" stroke="#798879" strokeWidth="1"><path d="M33 135V54L128 42V123Z"/><path d="M143 121V40L237 28V111Z"/><path d="M440 119V39L533 44V124Z"/><path d="M284 155 384 150 385 211 283 223Z"/><path d="M284 155 304 140 403 138 384 150ZM384 150 403 138 403 197 385 211Z" fill="#3b4b3b"/></g>
 {zones&&<g><path d="M104 207 437 175 515 286 81 319Z" fill="#bdd3a9" fillOpacity=".045" stroke="#9cab85" strokeDasharray="5 5"/><text x="107" y="296" fill="#9dab8f" fontSize="9" fontFamily="monospace">TEST ZONE / A</text></g>}
 <g className="scene-cart"><path d="M196 202 240 197 240 230 196 237Z" fill="#65715a"/><path d="M196 202 209 193 252 188 240 197Z" fill="#8a9377"/><path d="M240 197 252 188 252 218 240 230Z" fill="#414e3e"/>{boxes&&<><rect x="185" y="179" width="79" height="67" fill="none" stroke="#c7dcb0" strokeWidth="1"/><rect x="185" y="166" width="79" height="13" fill="#c7dcb0"/><text x="190" y="175" fill="#142018" fontSize="8" fontFamily="monospace">TEST OBJECT 01</text><path d="M224 247v13m-7-7h14" stroke="#c7dcb0"/></>}</g>
 <g opacity=".4" fill="none" stroke="#ccd3b3"><path d="M292 160h16m-8-8v16"/><path d="M10 25v-15h25m555 15v-15h-25M10 315v15h25m555-15v15h-25"/></g>
 </svg>}
 {index<2&&<div className="scene-scan"/>}<div className="scene-top"><span><i/>{index===2?'OFFLINE':'SYNTHETIC SCENE'}</span><span>{index===2?'—':'REC / LOOP 00:24'}</span></div><div className="scene-bottom"><span>PX / CONTROLLED ENVIRONMENT</span><span>CAM–0{index+1}</span></div>
 </div>;}
export function RelationMatrix({nodes,edges,onRelation}:{nodes:Entity[];edges:Connection[];onRelation:(id:string)=>void}){return <div className="matrix-wrap"><div className="matrix-grid" style={{gridTemplateColumns:`130px repeat(${nodes.length}, minmax(48px,1fr))`}}><span className="matrix-corner">ENTITY × ENTITY</span>{nodes.map(n=><span key={n.id} className="matrix-column" title={n.name}>{n.initials||n.name.slice(0,2).toUpperCase()}</span>)}{nodes.map((row,i)=><div className="matrix-row" key={row.id}><b>{row.name}</b>{nodes.map((col,j)=>{const links=edges.filter(e=>(e.from===row.id&&e.to===col.id)||(e.from===col.id&&e.to===row.id));const link=links[0];return <button key={col.id} className={`matrix-cell ${i===j?'diagonal':''} ${link?'linked':''} ${links.some(l=>l.status==='disputed')?'conflict-cell':''}`} disabled={!link} onClick={()=>link&&onRelation(link.id)} aria-label={`${row.name} and ${col.name}: ${links.map(l=>l.label).join(', ')||'no connection'}`} style={{'--cell-color':link?groups[link.group].color:undefined} as CSSProperties}>{i===j?'／':links.length>1?links.length:link?<i/>:'·'}</button>;})}</div>)}</div></div>;}
